
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Peer Production on the Crypto Commons"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

baseurl="/"

[Params]

    # Souce Code repository section
    description = "Toward a Commons Based Economy"
    github_repository = "https://github.com/RichardRed0x/ppcc/"
    version = "0.5"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/RichardRed0x/ppcc/"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [ "post", "posts", "blog", "img", "download"]


# Global menu section
[[menu.main]]
    name = "Read"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 2

[[menu.main]]
    name = "Block Commons"
    url = "http://www.blockcommons.red"
    weight = 3

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/blockcommons"
    weight = 4

